"""
Django settings for donation project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^1#amicvbfwr@ui#-91@%+j6jj3p4$7f(i-28@rw^0sey2j+p2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'dashboard',
    'category',
    'rest_framework',
    'api',
    'campaign',
    'users',
    'report',
    'table',
    'corsheaders',
    
    'rest_framework.authtoken',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    # 'django.contrib.sites.models.Site',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    'rest_framework_swagger',
]

SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

LOGIN_URL='/admin/'
ROOT_URLCONF = 'donation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'social_django.context_processors.backends',
                # 'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'donation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# DATABASES = {
#    'default': {
#        'NAME': 'donation',
#        'ENGINE': 'django.db.backends.mysql',
#        'USER': 'root',
#        'PASSWORD': '123456',
#        'HOST': 'localhost',
#        'PORT': '3306',
#        'OPTIONS': {
#            'autocommit': True,
#        },
#    }
# }

#for docker configuration
# DATABASES = {
#    'default': {
#        'NAME': 'donation',
#        'ENGINE': 'django.db.backends.mysql',
#        'USER': 'root',
#        'PASSWORD': '123456',
#        'HOST': 'db',
#        'PORT': '3306',
#        'OPTIONS': {
#            'autocommit': True,
#        },
#    }
# }

DATABASES = {
   'default': {
       'NAME': 'alaminshaks$default',
       'ENGINE': 'django.db.backends.mysql',
       'USER': 'alaminshaks',
       'PASSWORD': 'mind2high007',
       'HOST': 'alaminshaks.mysql.pythonanywhere-services.com',
       'PORT': '3306',
       'OPTIONS': {
           'autocommit': True,
       },
   }
}

# import psycopg2
# DATABASES = {
#    'default': {
#        'NAME': 'd9gp7l973155iv',
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'USER': 'smvwlrscixhlmu',
#        'PASSWORD': '68966e0c5dfbbbf8c588f3069518b95ab0aa8e8ca5f23deee8fc195f0481bd26',
#        'HOST': 'ec2-54-235-73-241.compute-1.amazonaws.com',
#        'PORT': '5432'

#    }
# }

#can be commented out for later
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config()
# }

# shak = 'awesome'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
BASE_URL='http://alaminshaks.pythonanywhere.com/'

# if DEBUG:
#     BASE_URL='http://localhost:8000/'


STATIC_URL='/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn")

MEDIA_URL ='media_cdn/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media_cdn")
CONTACT_MAIL = 'shakeelcse09@gmail.com'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = '1025'
EMAIL_USE_TLS = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}

REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER":"users.serializers.CustomRegisterSerializer"
}

# AUTHENTICATION_BACKENDS = (

#    'social.backends.facebook.FacebookOAuth2',
# )


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    'localhost:4200',
)
CORS_ORIGIN_REGEX_WHITELIST = (
    'localhost:4200',
)
CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'content-disposition',
    'media_type'
)

# SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
# SOCIALACCOUNT_EMAIL_REQUIRED = False
# SOCIALACCOUNT_QUERY_EMAIL = True
# try:
#from local_settings import *    
# except Exception as e:
#     pass

# import imp
try:
    # imp.find_module('local_settings')
    from local_settings import * 
except ImportError:
    pass
