# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:52
from __future__ import unicode_literals

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='content',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=campaign.models.uplaod_location, width_field=b'width_field'),
        ),
    ]
