# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20170815_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[(b'image', b'Image'), (b'file', b'File'), (b'video', b'Video'), (b'link', b'Link')], default=b'image', max_length=255),
        ),
    ]
