# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20170815_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='category',
        ),
        migrations.AddField(
            model_name='documents',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.Campaign'),
        ),
    ]
