# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:58
from __future__ import unicode_literals

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20170815_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to=campaign.models.uplaod_location),
        ),
    ]
