# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20170818_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='documents',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
