# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='content_resized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
