# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20180318_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialshare',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
